services:
  - type: web
    name: diani-calendar
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: INTERVALS_ATHLETE_ID
        sync: false
      - key: INTERVALS_API_KEY
        sync: false
      - key: WORLDTIDES_KEY
        sync: false
